version: '2'
volumes:
  redisvol:
services:
  web:
    image: shturmfest
    build: .
    command: python app.py
    ports:
     - "80:5000"
  redis:
    image: "redis:alpine"
    volumes:
       - redisvol:/data

